-- Rattache les tables de la partie Activités (ex-site anniversaire) à un
-- espace. Les tables existaient déjà en production (créées à la main) :
-- tout est écrit pour s'appliquer aussi bien sur une base vide que sur
-- l'existant.
--
-- Les lignes déjà présentes gardent espace_id = null et deviennent donc
-- invisibles : les rattacher à votre espace une fois celui-ci créé (voir
-- docs/SUPABASE.md, « Récupérer les données du site anniversaire »).

create table if not exists public.activites_carnet (
  id uuid primary key default gen_random_uuid(),
  nom_activite text not null,
  note int,
  commentaire text,
  photo_url text,
  date timestamp default now()
);

alter table public.activites_carnet
  add column if not exists date_activite timestamptz,
  add column if not exists mood_debut text,
  add column if not exists mood_fin text,
  add column if not exists espace_id uuid references public.espaces (id) on delete cascade;

create table if not exists public.messages_proches (
  id uuid primary key default gen_random_uuid(),
  auteur text not null,
  message text not null,
  photo_url text,
  date timestamp default now()
);

alter table public.messages_proches
  add column if not exists espace_id uuid references public.espaces (id) on delete cascade;

create table if not exists public.mots_passe_accueil (
  id bigint generated by default as identity primary key,
  mot_de_passe text not null,
  salutation text not null
);

alter table public.mots_passe_accueil
  add column if not exists espace_id uuid references public.espaces (id) on delete cascade;

create index if not exists activites_carnet_espace_id_idx on public.activites_carnet (espace_id);
create index if not exists messages_proches_espace_id_idx on public.messages_proches (espace_id);
create index if not exists mots_passe_accueil_espace_id_idx on public.mots_passe_accueil (espace_id);

-- Les anciennes policies (accès anonyme du site anniversaire) sont
-- supprimées : les policies Postgres s'additionnent, en garder une seule
-- ouverte rendrait visibles les données de tous les espaces.
do $$
declare
  p record;
begin
  for p in
    select policyname, tablename from pg_policies
    where schemaname = 'public'
      and tablename in ('activites_carnet', 'messages_proches', 'mots_passe_accueil')
  loop
    execute format('drop policy %I on public.%I', p.policyname, p.tablename);
  end loop;
end;
$$;

alter table public.activites_carnet enable row level security;
alter table public.messages_proches enable row level security;
alter table public.mots_passe_accueil enable row level security;

create policy "activites_carnet_membres" on public.activites_carnet for all
  using (public.est_membre(espace_id))
  with check (public.est_membre(espace_id));

create policy "messages_proches_membres" on public.messages_proches for all
  using (public.est_membre(espace_id))
  with check (public.est_membre(espace_id));

create policy "mots_passe_accueil_membres" on public.mots_passe_accueil for all
  using (public.est_membre(espace_id))
  with check (public.est_membre(espace_id));

-- ---------------------------------------------------------------------------
-- Photos du carnet : le bucket reste public en lecture (URL publiques déjà
-- enregistrées dans activites_carnet), l'envoi est réservé aux membres, dans
-- un dossier au nom de l'espace : <espace_id>/<fichier>
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('photos-carnet', 'photos-carnet', true)
on conflict (id) do nothing;

drop policy if exists "photos_carnet_envoi_membres" on storage.objects;
create policy "photos_carnet_envoi_membres" on storage.objects for insert to authenticated
  with check (
    bucket_id = 'photos-carnet'
    -- case plutôt que "and" : Postgres ne garantit pas l'ordre d'évaluation,
    -- et le cast ::uuid échouerait sur un nom de dossier quelconque
    and case
      when (storage.foldername(name))[1] ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        then public.est_membre(((storage.foldername(name))[1])::uuid)
      else false
    end
  );
